version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:633025986259:task-definition/test:4"
        LoadBalancerInfo:
          ContainerName: "sample-api"
          ContainerPort: 8086
