apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: my-app  # Match pods with this label
  template:
    metadata:
      labels:
        app: my-app  # Pod label
    spec:
      containers:
      - name: my-app-container
        image: public.ecr.aws/p2g3u3g4/leaf:latest  # Replace with your Docker image
        ports:
        - containerPort: 8086  # Port on which the application will run inside the container

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # This matches the pods with the label 'app: my-app'
  ports:
    - protocol: TCP
      port: 8086  # The internal port exposed by the service
      targetPort: 8080  # The port on which your application is running inside the pod
      nodePort: 30080  # The external port on which the service will be exposed on each node
  type: NodePort  # Exposes the service to external traffic via NodePort

